name: img_syn
dependencies:
    - python=3.7
    - tensorflow==2.0.0
    - pandas 
    - numpy
    - seaborn
    - matplotlib
    - tqdm
    - jupyter
    - opencv
    - scikit-learn
    - autopep8
    - voila
    - pip:
        - tf_explain
        - higra
        - opencv-contrib-python